name: adaj
version: 0.1.1
author: Egor Day <edaydev@gmail.com>
description: Primitive utility for asynchronous JSON requests with Dart. Sending JSON data is supported, as well, as simple success/error/always callbacks
homepage: https://github.com/daydev/adaj
dependencies:
  browser: any
  unittest: 0.8.10
